### ISSUE TITLE
Some checks fails on http://saml.oktadev.com/

### ISSUE THREAD

**Issue by dfournier** [jpf/okta-pysaml2-example#4]
Hi,

I followed the instructions but I got 2 failures on the test suite:
* Unexpected issue SP issue validating signed SAML
* The SP does not support a compressed SAMLResponse

Actually, it looks like the `SAMLResponse` content is unparsable. I get this error each time:
```
ERROR:saml2.client_base:XML parse error: syntax error: line 1, column 0
INFO:werkzeug:127.0.0.1 - - [29/May/2017 15:20:33] "POST /saml/sso/test HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/Users/davidfournier/workspace/okta-pysaml2-example/venv/lib/python2.7/site-packages/flask/app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
  File "/Users/davidfournier/workspace/okta-pysaml2-example/venv/lib/python2.7/site-packages/flask/app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/Users/davidfournier/workspace/okta-pysaml2-example/venv/lib/python2.7/site-packages/flask/app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/davidfournier/workspace/okta-pysaml2-example/venv/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/davidfournier/workspace/okta-pysaml2-example/venv/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/davidfournier/workspace/okta-pysaml2-example/venv/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/davidfournier/workspace/okta-pysaml2-example/venv/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/davidfournier/workspace/okta-pysaml2-example/venv/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/davidfournier/workspace/okta-pysaml2-example/app.py", line 159, in idp_initiated
    entity.BINDING_HTTP_POST)
  File "/Users/davidfournier/workspace/okta-pysaml2-example/venv/lib/python2.7/site-packages/saml2/client_base.py", line 599, in parse_authn_request_response
    binding, **kwargs)
  File "/Users/davidfournier/workspace/okta-pysaml2-example/venv/lib/python2.7/site-packages/saml2/entity.py", line 1137, in _parse_response
    response = response.loads(xmlstr, False, origxml=origxml)
  File "/Users/davidfournier/workspace/okta-pysaml2-example/venv/lib/python2.7/site-packages/saml2/response.py", line 510, in loads
    self._loads(xmldata, decode, origxml)
  File "/Users/davidfournier/workspace/okta-pysaml2-example/venv/lib/python2.7/site-packages/saml2/response.py", line 335, in _loads
    **args)
  File "/Users/davidfournier/workspace/okta-pysaml2-example/venv/lib/python2.7/site-packages/saml2/sigver.py", line 1734, in correctly_signed_response
    response = samlp.any_response_from_string(decoded_xml)
  File "/Users/davidfournier/workspace/okta-pysaml2-example/venv/lib/python2.7/site-packages/saml2/samlp.py", line 1847, in any_response_from_string
    resp = func(xmlstr)
  File "/Users/davidfournier/workspace/okta-pysaml2-example/venv/lib/python2.7/site-packages/saml2/samlp.py", line 1446, in status_response_type__from_string
    return saml2.create_class_from_xml_string(StatusResponseType_, xml_string)
  File "/Users/davidfournier/workspace/okta-pysaml2-example/venv/lib/python2.7/site-packages/saml2/__init__.py", line 89, in create_class_from_xml_string
    tree = ElementTree.fromstring(xml_string)
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xml/etree/ElementTree.py", line 1311, in XML
    parser.feed(text)
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xml/etree/ElementTree.py", line 1653, in feed
    self._raiseerror(v)
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xml/etree/ElementTree.py", line 1517, in _raiseerror
    raise err
ParseError: syntax error: line 1, column 0
```

Could you please confirm you have the same problem?

Best,
David

**Comment by earonesty** [comment]
does this fix it for you? https://github.com/IdentityPython/pysaml2/pull/895
